repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
# -   repo: https://github.com/psf/black
#     rev: 25.1.0
#     hooks:
#     -   id: black
# -   repo: https://github.com/pycqa/isort
#     rev: 6.0.0
#     hooks:
#       - id: isort
#         name: isort (python)
