activation: relu
base_model_path: /mnt/output/7240/ckpts/base-model-last.pt
batch_log: false
batch_size: 32
clip_update_threshold: 2.0
clip_updates: false
data_path: /media/lweber/f3ed2aae-a7bf-4a55-b50d-ea8fb534f1f51/Datasets/huggingface/oxford-flowers
dataset_name: oxford-flowers
default_model_checkpoint: google/vit-base-patch16-224-in21k
disable_wandb: false
epochs: 50
loss_name: ce-loss
lr: 2.0e-05
model_name: vit
momentum: 0.9
n_channels: 3
n_outputs: 3
optimizer_name: adamw
param_sparsity_log: false
propagator_name: lfp-epsilon
reward_kwargs: {}
reward_name: softmaxlossreward
savepath: /mnt/output/
scheduler_name: onecyclelr
seed: 7240
verbose: false
wandb_key: 343d642ebb6021c0303b16436ddf0be59cb0696f
wandb_project_name: code-testing-oxford-flowers-vit
weight_decay: 0.0
