activation: relu
base_data_path: /mnt/data/imagenet
base_dataset_name: imagenet
base_model_path: /mnt/output/5110/ckpts/base-model-last.pt
batch_log: false
batch_size: 32
clip_update_threshold: 2.0
clip_updates: false
disable_wandb: false
loss_name: ce-loss
model_name: vgg16bn
momentum: 0.9
n_channels: 3
norm_backward: false
propagator_name: vanilla-gradient
reward_kwargs: {}
reward_name: softmaxlossreward
savepath: /mnt/output
scheduler_name: onecyclelr
seed: 5110
transfer_data_path: /mnt/data/food11
transfer_dataset_name: food11
transfer_epochs: 100
transfer_lr: 0.001
transfer_training: true
verbose: false
wandb_key: <wandb-key>
wandb_project_name: imagenet-to-food11-transfer-vgg16bn
weight_decay: 0.0001
